//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAppWeb.DataManagementService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableSchema", Namespace="http://schemas.datacontract.org/2004/07/DataManagementService.Entity")]
    [System.SerializableAttribute()]
    public partial class TableSchema : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ColumnNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BankAppWeb.DataManagementService.Condition[] ConditionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConnectionStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ValuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ColumnNames {
            get {
                return this.ColumnNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnNamesField, value) != true)) {
                    this.ColumnNamesField = value;
                    this.RaisePropertyChanged("ColumnNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BankAppWeb.DataManagementService.Condition[] Conditions {
            get {
                return this.ConditionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ConditionsField, value) != true)) {
                    this.ConditionsField = value;
                    this.RaisePropertyChanged("Conditions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConnectionString {
            get {
                return this.ConnectionStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionStringField, value) != true)) {
                    this.ConnectionStringField = value;
                    this.RaisePropertyChanged("ConnectionString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderName {
            get {
                return this.ProviderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderNameField, value) != true)) {
                    this.ProviderNameField = value;
                    this.RaisePropertyChanged("ProviderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableName {
            get {
                return this.TableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TableNameField, value) != true)) {
                    this.TableNameField = value;
                    this.RaisePropertyChanged("TableName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Values {
            get {
                return this.ValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuesField, value) != true)) {
                    this.ValuesField = value;
                    this.RaisePropertyChanged("Values");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Condition", Namespace="http://schemas.datacontract.org/2004/07/DataManagementService.Entity")]
    [System.SerializableAttribute()]
    public partial class Condition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BankAppWeb.DataManagementService.Condition.Operator ConditionOperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BankAppWeb.DataManagementService.Condition.Conjunction ConjunctionOperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeftOperandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RightOperandField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BankAppWeb.DataManagementService.Condition.Operator ConditionOperator {
            get {
                return this.ConditionOperatorField;
            }
            set {
                if ((this.ConditionOperatorField.Equals(value) != true)) {
                    this.ConditionOperatorField = value;
                    this.RaisePropertyChanged("ConditionOperator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BankAppWeb.DataManagementService.Condition.Conjunction ConjunctionOperator {
            get {
                return this.ConjunctionOperatorField;
            }
            set {
                if ((this.ConjunctionOperatorField.Equals(value) != true)) {
                    this.ConjunctionOperatorField = value;
                    this.RaisePropertyChanged("ConjunctionOperator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeftOperand {
            get {
                return this.LeftOperandField;
            }
            set {
                if ((object.ReferenceEquals(this.LeftOperandField, value) != true)) {
                    this.LeftOperandField = value;
                    this.RaisePropertyChanged("LeftOperand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RightOperand {
            get {
                return this.RightOperandField;
            }
            set {
                if ((object.ReferenceEquals(this.RightOperandField, value) != true)) {
                    this.RightOperandField = value;
                    this.RaisePropertyChanged("RightOperand");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Condition.Operator", Namespace="http://schemas.datacontract.org/2004/07/DataManagementService.Entity")]
        public enum Operator : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            LessThan = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            GreaterThan = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            LessThanOrEqual = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            GreaterThanOrEqual = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Equal = 4,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Condition.Conjunction", Namespace="http://schemas.datacontract.org/2004/07/DataManagementService.Entity")]
        public enum Conjunction : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            And = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Or = 1,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultSet", Namespace="http://schemas.datacontract.org/2004/07/DataManagementService.Entity")]
    [System.SerializableAttribute()]
    public partial class ResultSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfRowsAffectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BankAppWeb.DataManagementService.Record[] RecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfRowsAffected {
            get {
                return this.NumberOfRowsAffectedField;
            }
            set {
                if ((this.NumberOfRowsAffectedField.Equals(value) != true)) {
                    this.NumberOfRowsAffectedField = value;
                    this.RaisePropertyChanged("NumberOfRowsAffected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BankAppWeb.DataManagementService.Record[] Records {
            get {
                return this.RecordsField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordsField, value) != true)) {
                    this.RecordsField = value;
                    this.RaisePropertyChanged("Records");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Record", Namespace="http://schemas.datacontract.org/2004/07/DataManagementService.Entity")]
    [System.SerializableAttribute()]
    public partial class Record : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ColumnsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Columns {
            get {
                return this.ColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnsField, value) != true)) {
                    this.ColumnsField = value;
                    this.RaisePropertyChanged("Columns");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustDetail", Namespace="http://schemas.datacontract.org/2004/07/DataManagementService.Entity")]
    [System.SerializableAttribute()]
    public partial class CustDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaritalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable dtCustomerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((object.ReferenceEquals(this.DOBField, value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaritalStatus {
            get {
                return this.MaritalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MaritalStatusField, value) != true)) {
                    this.MaritalStatusField = value;
                    this.RaisePropertyChanged("MaritalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable dtCustomer {
            get {
                return this.dtCustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.dtCustomerField, value) != true)) {
                    this.dtCustomerField = value;
                    this.RaisePropertyChanged("dtCustomer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataManagementService.IDataManagementService")]
    public interface IDataManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManagementService/GetDataFromTable", ReplyAction="http://tempuri.org/IDataManagementService/GetDataFromTableResponse")]
        BankAppWeb.DataManagementService.ResultSet GetDataFromTable(BankAppWeb.DataManagementService.TableSchema tableSchema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManagementService/GetDataFromTable", ReplyAction="http://tempuri.org/IDataManagementService/GetDataFromTableResponse")]
        System.Threading.Tasks.Task<BankAppWeb.DataManagementService.ResultSet> GetDataFromTableAsync(BankAppWeb.DataManagementService.TableSchema tableSchema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManagementService/AddCustomerDetail", ReplyAction="http://tempuri.org/IDataManagementService/AddCustomerDetailResponse")]
        bool AddCustomerDetail(BankAppWeb.DataManagementService.CustDetail customerDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManagementService/AddCustomerDetail", ReplyAction="http://tempuri.org/IDataManagementService/AddCustomerDetailResponse")]
        System.Threading.Tasks.Task<bool> AddCustomerDetailAsync(BankAppWeb.DataManagementService.CustDetail customerDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManagementService/GetCustomerDetails", ReplyAction="http://tempuri.org/IDataManagementService/GetCustomerDetailsResponse")]
        BankAppWeb.DataManagementService.GetCustomerDetailsResponse GetCustomerDetails(BankAppWeb.DataManagementService.GetCustomerDetailsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManagementService/GetCustomerDetails", ReplyAction="http://tempuri.org/IDataManagementService/GetCustomerDetailsResponse")]
        System.Threading.Tasks.Task<BankAppWeb.DataManagementService.GetCustomerDetailsResponse> GetCustomerDetailsAsync(BankAppWeb.DataManagementService.GetCustomerDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManagementService/InsertCustomerData", ReplyAction="http://tempuri.org/IDataManagementService/InsertCustomerDataResponse")]
        bool InsertCustomerData(BankAppWeb.DataManagementService.CustDetail customerDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManagementService/InsertCustomerData", ReplyAction="http://tempuri.org/IDataManagementService/InsertCustomerDataResponse")]
        System.Threading.Tasks.Task<bool> InsertCustomerDataAsync(BankAppWeb.DataManagementService.CustDetail customerDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManagementService/GetCustomerList", ReplyAction="http://tempuri.org/IDataManagementService/GetCustomerListResponse")]
        BankAppWeb.DataManagementService.ResultSet GetCustomerList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManagementService/GetCustomerList", ReplyAction="http://tempuri.org/IDataManagementService/GetCustomerListResponse")]
        System.Threading.Tasks.Task<BankAppWeb.DataManagementService.ResultSet> GetCustomerListAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerDetails", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerDetailsRequest {
        
        public GetCustomerDetailsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerDetailsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public BankAppWeb.DataManagementService.ResultSet GetCustomerDetailsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int NoOfRecords;
        
        public GetCustomerDetailsResponse() {
        }
        
        public GetCustomerDetailsResponse(BankAppWeb.DataManagementService.ResultSet GetCustomerDetailsResult, int NoOfRecords) {
            this.GetCustomerDetailsResult = GetCustomerDetailsResult;
            this.NoOfRecords = NoOfRecords;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataManagementServiceChannel : BankAppWeb.DataManagementService.IDataManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataManagementServiceClient : System.ServiceModel.ClientBase<BankAppWeb.DataManagementService.IDataManagementService>, BankAppWeb.DataManagementService.IDataManagementService {
        
        public DataManagementServiceClient() {
        }
        
        public DataManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BankAppWeb.DataManagementService.ResultSet GetDataFromTable(BankAppWeb.DataManagementService.TableSchema tableSchema) {
            return base.Channel.GetDataFromTable(tableSchema);
        }
        
        public System.Threading.Tasks.Task<BankAppWeb.DataManagementService.ResultSet> GetDataFromTableAsync(BankAppWeb.DataManagementService.TableSchema tableSchema) {
            return base.Channel.GetDataFromTableAsync(tableSchema);
        }
        
        public bool AddCustomerDetail(BankAppWeb.DataManagementService.CustDetail customerDetail) {
            return base.Channel.AddCustomerDetail(customerDetail);
        }
        
        public System.Threading.Tasks.Task<bool> AddCustomerDetailAsync(BankAppWeb.DataManagementService.CustDetail customerDetail) {
            return base.Channel.AddCustomerDetailAsync(customerDetail);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankAppWeb.DataManagementService.GetCustomerDetailsResponse BankAppWeb.DataManagementService.IDataManagementService.GetCustomerDetails(BankAppWeb.DataManagementService.GetCustomerDetailsRequest request) {
            return base.Channel.GetCustomerDetails(request);
        }
        
        public BankAppWeb.DataManagementService.ResultSet GetCustomerDetails(out int NoOfRecords) {
            BankAppWeb.DataManagementService.GetCustomerDetailsRequest inValue = new BankAppWeb.DataManagementService.GetCustomerDetailsRequest();
            BankAppWeb.DataManagementService.GetCustomerDetailsResponse retVal = ((BankAppWeb.DataManagementService.IDataManagementService)(this)).GetCustomerDetails(inValue);
            NoOfRecords = retVal.NoOfRecords;
            return retVal.GetCustomerDetailsResult;
        }
        
        public System.Threading.Tasks.Task<BankAppWeb.DataManagementService.GetCustomerDetailsResponse> GetCustomerDetailsAsync(BankAppWeb.DataManagementService.GetCustomerDetailsRequest request) {
            return base.Channel.GetCustomerDetailsAsync(request);
        }
        
        public bool InsertCustomerData(BankAppWeb.DataManagementService.CustDetail customerDetail) {
            return base.Channel.InsertCustomerData(customerDetail);
        }
        
        public System.Threading.Tasks.Task<bool> InsertCustomerDataAsync(BankAppWeb.DataManagementService.CustDetail customerDetail) {
            return base.Channel.InsertCustomerDataAsync(customerDetail);
        }
        
        public BankAppWeb.DataManagementService.ResultSet GetCustomerList() {
            return base.Channel.GetCustomerList();
        }
        
        public System.Threading.Tasks.Task<BankAppWeb.DataManagementService.ResultSet> GetCustomerListAsync() {
            return base.Channel.GetCustomerListAsync();
        }
    }
}
